# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
              users:
                admin: { password: $2y$12$xmPAOHtOPJpNz/83dXYOHuTi3hPBv3bc/ZPh2ZD.0bOGJtpO0VzWW, roles: [ 'ROLE_ADMIN', 'ROLE_API' ] }
                api_user:  { password: $2y$12$UDu0n4JCYK8ZibPqkDxXW.CFJHPkGTcvjmdAIcKZiGgUaEtqkVzxi, roles: [ 'ROLE_API' ] }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            anonymous: ~
            http_basic: true

    access_control:
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/web/users, roles: ROLE_ADMIN }

    encoders:
            Symfony\Component\Security\Core\User\User:
                    algorithm: bcrypt
                    cost: 12